### PR TITLE
Update ProjectDocs.pm

### PR DESCRIPTION
**Pull request by 1nickt**
This PR tries to improve link handling.

1. In order to make hyperlinks to other local `*.pod`and `*.pl` files work, include files from all Managers in `@perl_modules` (renamed to `@perl_files`).

( Currently, only `*.pm` modules are included in the `@perl_modules` list, meaning that POD markup like `L<my_other_manual>` is rendered as a link to a search of CPAN, even if `my_other_manual.pod` is included to be processed. )

2. In order to make hyperlinks to sections in the same or a different page work, replace spaces with underscores in the link target.

( So that markup like `L<my_other_manual/Some Section>` produces a link like `<a href="my_other_manual.pod.html#Some_Section">`, which matches the anchor name created when `my_other_manual.pod.html` was created.)

### CODE REVIEW

**Comment by 1nickt** [comment]
Hi Martin,

Not sure if URI::Escape would be the solution, unless we also modify how
the anchor names generated elsewhere from the =head sections.

This change accepts that the anchor names are generated with spaces
replaced by underscores, and follows suit.

I'd be happy to write some tests for it, let me know what you think when
you've had a chance to look at the changes.

Thank you for your attention, and Happy New Year!

~nick

**Comment by mgruner** [comment]
Hi @1nickt. Just to let you know, I'm currently working on a rewrite of the Pod parser in a separate branch (https://github.com/mgruner/p5-pod-projectdocs/commits/pod-simple-xhtml). It seems to be already working and solves the section link issue. We might have to look at the other problem again after this goes live in master. 
I'd appreciate any feedback you might have on this rewrite.
Best regards, Martin

**Comment by mgruner** [comment]
Hello, @1nickt. Can you please try again with the current version of this module? It has been largely rewritten, using a new engine based on Pod::Simple::XHTML.

**Comment by 1nickt** [comment]
Hi Martin,

I will get to this in the next few days. Looking forward to trying it,
thanks!

**Pull request closed without merging**
